import { StyleSheet } from '@react-pdf/renderer';

export const colors = {
  primary: '#1a365d',
  secondary: '#2d3748',
  accent: '#38a169',
  warning: '#e53e3e',
  text: '#2d3748',
  lightBg: '#f7fafc',
  border: '#e2e8f0',
  white: '#ffffff',
};

export const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 10,
    fontFamily: 'Helvetica',
    color: colors.text,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    paddingBottom: 15,
    borderBottomWidth: 2,
    borderBottomColor: colors.primary,
  },
  logo: {
    width: 120,
    height: 50,
    objectFit: 'contain',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.primary,
    textAlign: 'right',
  },
  headerSubtitle: {
    fontSize: 10,
    color: colors.secondary,
    textAlign: 'right',
  },
  referenceBox: {
    backgroundColor: colors.primary,
    color: colors.white,
    padding: 10,
    marginTop: 10,
    marginBottom: 20,
    textAlign: 'center',
  },
  referenceNumber: {
    fontSize: 16,
    fontWeight: 'bold',
    letterSpacing: 2,
  },
  section: {
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    color: colors.primary,
    backgroundColor: colors.lightBg,
    padding: 8,
    marginBottom: 10,
    borderLeftWidth: 3,
    borderLeftColor: colors.primary,
  },
  sectionTitleBilingual: {
    fontSize: 10,
    fontWeight: 'normal',
    color: colors.secondary,
  },
  table: {
    width: '100%',
    marginBottom: 10,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    minHeight: 25,
    alignItems: 'center',
  },
  tableRowAlt: {
    backgroundColor: colors.lightBg,
  },
  tableLabel: {
    width: '40%',
    padding: 6,
    fontSize: 9,
    color: colors.secondary,
  },
  tableLabelBilingual: {
    fontSize: 8,
    color: '#718096',
  },
  tableValue: {
    width: '60%',
    padding: 6,
    fontSize: 10,
  },
  declarationItem: {
    flexDirection: 'row',
    marginBottom: 2,
    paddingBottom: 2,
  },
  declarationCheck: {
    width: 20,
    marginRight: 10,
    color: colors.accent,
    fontSize: 10,
  },
  declarationCheckFailed: {
    color: colors.warning,
  },
  declarationText: {
    fontSize: 8,
    lineHeight: 9,
  },
  declarationTextAf: {
    fontSize: 7,
    color: colors.secondary,
    marginTop: 1,
    lineHeight: 8,
  },
  signatureBox: {
    borderWidth: 1,
    borderColor: colors.border,
    padding: 15,
    marginTop: 10,
    backgroundColor: colors.white,
  },
  signatureImage: {
    width: 200,
    height: 80,
    objectFit: 'contain',
  },
  signatureLabel: {
    fontSize: 9,
    color: colors.secondary,
    marginTop: 5,
  },
  attachmentContainer: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 10,
  },
  attachmentImage: {
    maxWidth: '100%',
    maxHeight: 300,
    objectFit: 'contain',
  },
  attachmentLabel: {
    fontSize: 9,
    color: colors.secondary,
    marginBottom: 5,
    fontStyle: 'italic',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: 10,
  },
  footerText: {
    fontSize: 7,
    color: colors.secondary,
    textAlign: 'center',
    marginBottom: 3,
  },
  footerDisclaimer: {
    fontSize: 6,
    color: colors.secondary,
    textAlign: 'center',
    fontStyle: 'italic',
    marginTop: 5,
  },
  pageNumber: {
    position: 'absolute',
    bottom: 30,
    right: 40,
    fontSize: 8,
    color: colors.secondary,
  },
  qrCodeContainer: {
    position: 'absolute',
    top: 10,
    right: 10,
    padding: 5,
    backgroundColor: colors.white,
  },
  qrCode: {
    width: 60,
    height: 60,
  },
  movementFlow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
    padding: 10,
    backgroundColor: colors.lightBg,
  },
  movementBox: {
    width: '30%',
    padding: 8,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    textAlign: 'center',
  },
  movementArrow: {
    fontSize: 16,
    color: colors.primary,
  },
  movementLabel: {
    fontSize: 8,
    fontWeight: 'bold',
    color: colors.primary,
    marginBottom: 3,
  },
  movementValue: {
    fontSize: 7,
    color: colors.text,
  },
  twoColumn: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  column: {
    width: '48%',
  },
  statusBadge: {
    backgroundColor: colors.accent,
    color: colors.white,
    padding: '4 8',
    fontSize: 8,
    borderRadius: 3,
  },
  divider: {
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    marginVertical: 10,
  },
});

export const labels = {
  en: {
    title: 'LIVESTOCK MOVEMENT DECLARATION',
    reference: 'Reference Number',
    dateIssued: 'Date Issued',
    status: 'Status',
    readyForLoading: 'Ready for Loading',
    sellerInfo: 'SELLER INFORMATION',
    ownerName: 'Owner Name',
    company: 'Company',
    email: 'Email',
    phone: 'Phone',
    livestockDetails: 'LIVESTOCK DETAILS',
    breed: 'Breed',
    totalOffered: 'Total Livestock Offered',
    males: 'Number of Males',
    females: 'Number of Females',
    castrated: 'Males Castrated',
    weanedDuration: 'Weaned Duration',
    growthImplant: 'Growth Implant',
    farmInfo: 'FARM & GLN INFORMATION',
    farmName: 'Farm Name',
    district: 'District',
    province: 'Province',
    glnNumber: 'GLN Number',
    glnQualified: 'GLN Premium Qualified',
    movementTracker: 'MOVEMENT TRACKER',
    birthAddress: 'Birth Address',
    currentAddress: 'Current Address',
    loadingAddress: 'Loading Address',
    movedOutOfBoundaries: 'Livestock Moved Out of Boundaries',
    movedFromLabel: 'Location where livestock was moved from',
    movedToLabel: 'Location where livestock was moved to',
    movedWhenLabel: 'When was the livestock moved there?',
    movedHowLabel: 'How were they moved?',
    biosecurity: 'BIOSECURITY DECLARATIONS',
    vetDeclaration: 'VETERINARY DECLARATION',
    vetName: 'Veterinarian Name',
    savcNumber: 'SAVC Registration No.',
    practiceName: 'Practice Name',
    inspectionDate: 'Inspection Date',
    vetSignature: 'Veterinarian Signature',
    loadMaster: 'LOAD MASTER DETAILS',
    loadMasterName: 'Load Master Name',
    truckReg: 'Truck Registration',
    cattleLoaded: 'Cattle Loaded',
    sheepLoaded: 'Sheep Loaded',
    sellerSignature: 'SELLER DECLARATION & SIGNATURE',
    sellerDeclarationText:
      'I, the undersigned, hereby declare that all information provided in this document is true and accurate to the best of my knowledge.',
    signedAt: 'Signed at',
    signedDate: 'Date',
    attachments: 'SUPPORTING DOCUMENTS',
    glnDocument: 'GLN Registration Document',
    affidavit: 'Affidavit',
    yes: 'Yes',
    no: 'No',
    notApplicable: 'N/A',
    sameAsBirth: 'Same as birth address',
    sameAsCurrent: 'Same as current address',
    generatedOn: 'Document generated on',
    documentId: 'Document ID',
    officialUse: 'OFFICIAL USE ONLY',
  },
  af: {
    title: 'VEEBEWEGING VERKLARING',
    reference: 'Verwysingsnommer',
    dateIssued: 'Datum Uitgereik',
    status: 'Status',
    readyForLoading: 'Gereed vir Laai',
    sellerInfo: 'VERKOPER INLIGTING',
    ownerName: 'Eienaar Naam',
    company: 'Maatskappy',
    email: 'E-pos',
    phone: 'Telefoon',
    livestockDetails: 'VEE BESONDERHEDE',
    breed: 'Ras',
    totalOffered: 'Totale Vee Aangebied',
    males: 'Aantal Bulkalwers',
    females: 'Aantal Verskalwers',
    castrated: 'Bulkalwers Gekastreer',
    weanedDuration: 'Speen Tydperk',
    growthImplant: 'Groei Inplanting',
    farmInfo: 'PLAAS & GLN INLIGTING',
    farmName: 'Plaasnaam',
    district: 'Distrik',
    province: 'Provinsie',
    glnNumber: 'GLN Nommer',
    glnQualified: 'GLN Premie Gekwalifiseer',
    movementTracker: 'BEWEGING SPOORSNYER',
    birthAddress: 'Geboorte Adres',
    currentAddress: 'Huidige Adres',
    loadingAddress: 'Laai Adres',
    movedOutOfBoundaries: 'Vee Buite Grense Beweeg',
    movedFromLabel: 'Plek waar vee vandaan geskuif is',
    movedToLabel: 'Plek waarheen vee geskuif is',
    movedWhenLabel: 'Wanneer is die vee daarheen geskuif?',
    movedHowLabel: 'Hoe is hulle geskuif?',
    biosecurity: 'BIOSEKURITEIT VERKLARINGS',
    vetDeclaration: 'VEEARTS VERKLARING',
    vetName: 'Veearts Naam',
    savcNumber: 'SAVR Registrasie Nr.',
    practiceName: 'Praktyk Naam',
    inspectionDate: 'Inspeksie Datum',
    vetSignature: 'Veearts Handtekening',
    loadMaster: 'LAAI MEESTER BESONDERHEDE',
    loadMasterName: 'Laai Meester Naam',
    truckReg: 'Vragmotor Registrasie',
    cattleLoaded: 'Beeste Gelaai',
    sheepLoaded: 'Skape Gelaai',
    sellerSignature: 'VERKOPER VERKLARING & HANDTEKENING',
    sellerDeclarationText:
      'Ek, die ondergetekende, verklaar hiermee dat alle inligting in hierdie dokument waar en akkuraat is na die beste van my kennis.',
    signedAt: 'Geteken te',
    signedDate: 'Datum',
    attachments: 'ONDERSTEUNENDE DOKUMENTE',
    glnDocument: 'GLN Registrasie Dokument',
    affidavit: 'Beëdigde Verklaring',
    yes: 'Ja',
    no: 'Nee',
    notApplicable: 'N.v.t.',
    sameAsBirth: 'Dieselfde as geboorte adres',
    sameAsCurrent: 'Dieselfde as huidige adres',
    generatedOn: 'Dokument gegenereer op',
    documentId: 'Dokument ID',
    officialUse: 'SLEGS VIR AMPTELIKE GEBRUIK',
  },
};

export const bilingualLabel = (key: keyof typeof labels.en) => ({
  en: labels.en[key],
  af: labels.af[key],
});

