// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtfnnkrmvpmmsvciejmv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0Zm5ua3JtdnBtbXN2Y2llam12Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMjgyNzUsImV4cCI6MjA2NTkwNDI3NX0.JszpCfiJjk-pc_tpEKuRkC7a_n3M0mLaV_aNDSbUNpE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);